// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the app.
///
/// Run `dart run flutterfire_cli:flutterfire configure --project=adnan-ullah-portfolio`
/// to replace this with your project's config.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCk5_vBv2mbJmJ6dVNZAVpgop0CDeDx1iQ",
      authDomain: "adnan-ullah-portfolio.firebaseapp.com",
      projectId: "adnan-ullah-portfolio",
      storageBucket: "adnan-ullah-portfolio.firebasestorage.app",
      messagingSenderId: "732812453376",
      appId: "1:732812453376:web:962843b0a611c991a0dae5",
      measurementId: "G-5DDP36G8M6");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'adnan-ullah-portfolio',
    storageBucket: 'adnan-ullah-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'adnan-ullah-portfolio',
    storageBucket: 'adnan-ullah-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.adnanUllah',
  );
}
